/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import control.Controller;
import global.Global;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Marci
 */
public class InfoPanel extends javax.swing.JPanel {

    private BufferedImage wallpaperImg;
    private Controller controller;

    ImageIcon menuButtonImage = new ImageIcon(this.getClass().getResource("/kepek/menu_button.png"));
    ImageIcon menuButtonLightImage = new ImageIcon(this.getClass().getResource("/kepek/menu_button_light.png"));
    ImageIcon menuButtonDarkImage = new ImageIcon(this.getClass().getResource("/kepek/menu_button_dark.png"));

    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
        setting();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int pointX = 0, pointY = 0,
                width = this.getWidth(),
                height = this.getHeight();
        g.drawImage(wallpaperImg, pointX, pointY, width, height, null);
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblGameGoal = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPaddleDescription = new javax.swing.JLabel();
        lblHaveFun = new javax.swing.JLabel();
        lblBallDescription = new javax.swing.JLabel();

        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOk.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/menu_button.png"))); // NOI18N
        btnOk.setText("Rendben");
        btnOk.setBorderPainted(false);
        btnOk.setContentAreaFilled(false);
        btnOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOkMouseReleased(evt);
            }
        });
        add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 139, 37));

        lblGameGoal.setEditable(false);
        lblGameGoal.setColumns(20);
        lblGameGoal.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        lblGameGoal.setForeground(new java.awt.Color(204, 204, 204));
        lblGameGoal.setLineWrap(true);
        lblGameGoal.setRows(5);
        lblGameGoal.setText("A játék célja, hogy minél tovább bírd, és minél több pontot szerezz. A feladat, hogy visszaüsd a labdát. Minden labdaütésért egy pont jár. Ha háromszor leesik, a játéknak vége.");
        lblGameGoal.setWrapStyleWord(true);
        lblGameGoal.setAutoscrolls(false);
        lblGameGoal.setBorder(null);
        lblGameGoal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblGameGoal.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        lblGameGoal.setEnabled(false);
        lblGameGoal.setOpaque(false);
        jScrollPane1.setViewportView(lblGameGoal);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 118));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/ball_blue.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/blue_paddle_image.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 29));

        lblPaddleDescription.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        lblPaddleDescription.setForeground(new java.awt.Color(204, 204, 204));
        lblPaddleDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaddleDescription.setText("A tálca, amivel ütsz.");
        add(lblPaddleDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 400, 29));

        lblHaveFun.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        lblHaveFun.setForeground(new java.awt.Color(204, 204, 204));
        lblHaveFun.setText("Jó szórakozást!");
        add(lblHaveFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 186, 37));

        lblBallDescription.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        lblBallDescription.setForeground(new java.awt.Color(204, 204, 204));
        lblBallDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBallDescription.setText("A labda, amit vissza kell ütni");
        add(lblBallDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 400, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseEntered
        btnOk.setIcon(menuButtonLightImage);
        controller.buttonEnteredEffect();
    }//GEN-LAST:event_btnOkMouseEntered

    private void btnOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseExited
        btnOk.setIcon(menuButtonImage);
    }//GEN-LAST:event_btnOkMouseExited

    private void btnOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMousePressed
        btnOk.setIcon(menuButtonDarkImage);
        controller.buttonPressedEffect();
    }//GEN-LAST:event_btnOkMousePressed

    private void btnOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseReleased
        btnOk.setIcon(menuButtonImage);
        controller.exitInfoFrame();
    }//GEN-LAST:event_btnOkMouseReleased

    private void setting() {
        try {
            wallpaperImg = ImageIO.read(this.getClass().getResourceAsStream(Global.INFO_PANEL_IMAGE));
        } catch (IOException ex) {
            Logger.getLogger(MenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);

        lblGameGoal.setBorder(null);
        lblGameGoal.setBackground(new Color(0, 0, 0, 0));

        Toolkit toolKit = Toolkit.getDefaultToolkit();
        Image cursorImage = new ImageIcon(this.getClass().getResource("/kepek/cursor_image_blue.png")).getImage();
        Point pont = new Point(0, 0);
        Cursor cursor = toolKit.createCustomCursor(cursorImage, pont, "Cursor");

        this.setCursor(cursor);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBallDescription;
    private javax.swing.JTextArea lblGameGoal;
    private javax.swing.JLabel lblHaveFun;
    private javax.swing.JLabel lblPaddleDescription;
    // End of variables declaration//GEN-END:variables

    public void languageSetting(ResourceBundle bundle) {
        btnOk.setText(bundle.getString("btnOk.text"));
        lblGameGoal.setText(bundle.getString("lblGameGoal.text"));
        lblBallDescription.setText(bundle.getString("lblBallDescription.text"));
        lblPaddleDescription.setText(bundle.getString("lblPaddleDescription.text"));
        lblHaveFun.setText(bundle.getString("lblHaveFun.text"));
    }
}
