/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import control.Controller;
import control.MainFrame;
import global.Global;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Marci
 */
public class MenuPanel extends javax.swing.JPanel {

    Controller controller;
    BufferedImage wallpaperImg;
    int xMouse;
    int yMouse;

    ImageIcon exitButtonImage = new ImageIcon(this.getClass().getResource("/kepek/exit_button.png"));
    ImageIcon exitButtonPressedImage = new ImageIcon(this.getClass().getResource("/kepek/exit_button_pressed.png"));
    ImageIcon minimizeButtonImage = new ImageIcon(this.getClass().getResource("/kepek/minimize_button.png"));
    ImageIcon minimizeButtonPressedImage = new ImageIcon(this.getClass().getResource("/kepek/minimize_button_pressed.png"));
    ImageIcon infoButtonImage = new ImageIcon(this.getClass().getResource("/kepek/info_button.png"));
    ImageIcon infoButtonPressedImage = new ImageIcon(this.getClass().getResource("/kepek/info_button_pressed.png"));
    ImageIcon menuButtonImage = new ImageIcon(this.getClass().getResource("/kepek/menu_button.png"));
    ImageIcon menuButtonLightImage = new ImageIcon(this.getClass().getResource("/kepek/menu_button_light.png"));
    ImageIcon menuButtonDarkImage = new ImageIcon(this.getClass().getResource("/kepek/menu_button_dark.png"));

    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
        setting();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int pointX = 0, pointY = 0,
                width = this.getWidth(),
                height = this.getHeight();
        g.drawImage(wallpaperImg, pointX, pointY, width, height, null);
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnResults = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnPaddle = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStart.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(204, 204, 204));
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/menu_button.png"))); // NOI18N
        btnStart.setText("Indítás");
        btnStart.setToolTipText("");
        btnStart.setBorderPainted(false);
        btnStart.setContentAreaFilled(false);
        btnStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStartMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStartMouseReleased(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 30));

        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 30));

        btnResults.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        btnResults.setForeground(new java.awt.Color(204, 204, 204));
        btnResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/menu_button.png"))); // NOI18N
        btnResults.setText("Eredmények");
        btnResults.setBorderPainted(false);
        btnResults.setContentAreaFilled(false);
        btnResults.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResultsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResultsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnResultsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnResultsMouseReleased(evt);
            }
        });
        add(btnResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 30));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/exit_button.png"))); // NOI18N
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });
        add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        btnPaddle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/minimize_button.png"))); // NOI18N
        btnPaddle.setBorderPainted(false);
        btnPaddle.setContentAreaFilled(false);
        btnPaddle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPaddleMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPaddleMouseReleased(evt);
            }
        });
        add(btnPaddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 30, 30));

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/info_button.png"))); // NOI18N
        btnInfo.setBorderPainted(false);
        btnInfo.setContentAreaFilled(false);
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInfoMouseReleased(evt);
            }
        });
        add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (txtName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nem írtál be nevet!");
        } else {
            controller.gameStart(txtName.getText());
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        btnExit.setIcon(exitButtonPressedImage);
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        btnExit.setIcon(exitButtonImage);
        int selectedOption = JOptionPane.showConfirmDialog(null, "Biztos ki akarsz lépni?", "Válassz", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnPaddleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaddleMousePressed
        btnPaddle.setIcon(minimizeButtonPressedImage);
    }//GEN-LAST:event_btnPaddleMousePressed

    private void btnPaddleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaddleMouseReleased
        btnPaddle.setIcon(minimizeButtonImage);
        ((JFrame) SwingUtilities.getWindowAncestor(this)).setState(MainFrame.ICONIFIED);
    }//GEN-LAST:event_btnPaddleMouseReleased

    private void btnInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMousePressed
        btnInfo.setIcon(infoButtonPressedImage);
    }//GEN-LAST:event_btnInfoMousePressed

    private void btnInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseReleased
        btnInfo.setIcon(infoButtonImage);
        controller.infoStart();
    }//GEN-LAST:event_btnInfoMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int xScreen = evt.getXOnScreen();
        int yScreen = evt.getYOnScreen();

        ((JFrame) SwingUtilities.getWindowAncestor(this)).setLocation(xScreen - xMouse, yScreen - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        btnStart.setIcon(menuButtonLightImage);
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        btnStart.setIcon(menuButtonImage);
    }//GEN-LAST:event_btnStartMouseExited

    private void btnStartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMousePressed
        btnStart.setIcon(menuButtonDarkImage);
    }//GEN-LAST:event_btnStartMousePressed

    private void btnStartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseReleased
        btnStart.setIcon(menuButtonImage);
    }//GEN-LAST:event_btnStartMouseReleased

    private void btnResultsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultsMouseEntered
        btnResults.setIcon(menuButtonLightImage);
    }//GEN-LAST:event_btnResultsMouseEntered

    private void btnResultsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultsMouseExited
        btnResults.setIcon(menuButtonImage);
    }//GEN-LAST:event_btnResultsMouseExited

    private void btnResultsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultsMousePressed
        btnResults.setIcon(menuButtonDarkImage);
    }//GEN-LAST:event_btnResultsMousePressed

    private void btnResultsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultsMouseReleased
        btnResults.setIcon(menuButtonImage);
    }//GEN-LAST:event_btnResultsMouseReleased

    private void setting() {
        try {
            wallpaperImg = ImageIO.read(this.getClass().getResourceAsStream(Global.MENU_IMAGE));
        } catch (IOException ex) {
            Logger.getLogger(MenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        Toolkit toolKit = Toolkit.getDefaultToolkit();
        Image cursorImage = new ImageIcon(this.getClass().getResource("/kepek/cursor_image_blue.png")).getImage();
        Point pont = new Point(0, 0);
        Cursor cursor = toolKit.createCustomCursor(cursorImage, pont, "Cursor");

        this.setCursor(cursor);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnPaddle;
    private javax.swing.JButton btnResults;
    private javax.swing.JButton btnStart;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
